### ISSUE TITLE
standalone?

### ISSUE THREAD

**Issue by simonleary-umass-edu** [thomas-krenn/check_ipmi_sensor_v3#55]
Can this script work without Nagios, Icinga or Icinga 2?

**Comment by veitw** [comment]
Sure, just as for all Nagios checks, you can simply use the script's exit code to determine the status (0==OK, 1==WARNING, 2==CRITICAL, 3==UNKNOWN) and then decide what to do with the check's output from stdout accordingly.

E. g. discard on exit 0 and output otherwise, so this can be a cronjob-oneliner sending you an e-mail if anything is wrong but stay silent if everything is ok.

**Comment by gschoenberger** [comment]
@veitw True!
